### ISSUE TITLE
asdf writer

### ISSUE THREAD

**Issue by wjlei1990** [jas11/specfem3d_globe#1]
### 1. stationxml

* station coordinates is not correct.

  I compared the station coordinates in stationxml and DATA/STATIONS file and found they are different. It seems one station coordinates is put into another station.

* channel_coordinates not working

  By adding two more attributes in channel level will fix this issue, "starttime" and "endtime". I am thinking about we can set the starttime as the beginning of the simulation time and endtime as the end of simulation time

* Azimuth not correct.

  For North, the azimuth should be zero and for East, the azimuth should be 90, which is flipped over in asdf file.

### 2. waveform

* for the begin time, there is a few seconds shift in sac output and asdf output. Need to be checked carefully. The correct form to calculate begin time in asdf is:
```
begin_time = pde_time + time_shift - 1.5 * half_duration
```
as stated in specfem manual

**Comment by jas11** [comment]
I have fixed all these issues. Please try the latest version. Please let me know if there are more issues with the writer. Thanks!
