### ISSUE TITLE
event pde time wrong

### ISSUE THREAD

**Issue by wjlei1990** [jas11/specfem3d_globe#2]
Hi James,

#### Quakeml
* The pde time stored in quakeml of synthetic.h5 is wrong. The pde time stored in the file is the same as cmt time, which should not be the case.
* I think the two magnitude in cmt file is mb and ms.
* Are you sure the source time function is triangle? I think the default one maybe gausssian? I am not so sure, need confirmation...

#### Stationxml
* station depth is wrong(latitude is put into the depth slot)

**Comment by jas11** [comment]
Thanks for reporting. These are all fixed, except for the source time function, which I left as a triangle since it's not needed for any applications yet.
