### ISSUE TITLE
writing asdf takes really long on large number of nodes on TITAN

### ISSUE THREAD

**Issue by wjlei1990** [jas11/specfem3d_globe#4]
Youyi and I are doing some test on the new specfem3d_globe with asdf writer.

We recently found that the writing operation is really slow on large number of processors if you have large number of stations. For example, if we uses 256 resolution, that will take 8*8*6 GPUs(nodes) on titan. Typically, the station file contains more than 1,600 stations. The forward simulation only takes 3min and 43 sec. However, the writing operation(asdf writer) took more than 11min.

I am guessing something in asdf writer is really slow. Maybe some MPI operations(broadcast and all gather, for example), or the reading the provenance file or so.

I am going to look into this problem recently cause we really need to get it done by as soon as possible. 

@mpbl @jas11 could you give me some advise how to fix it quickly?

**Comment by jas11** [comment]
I did a simulation for 2000 receivers with no auxiliary writing or provenance and the writing time went from 300 s (with provenance and auxiliary) to 60 s. This was only 0.5 minute trace. The auxiliary and provenance have to be done on all processers. I'm not sure what else would improve the writing time speed.

**Comment by wjlei1990** [comment]
I don't think the provenance and auxiliary data should be written on all processors. Should the master node be enough for that?

I am gonna to talk with you tomorrow.
