### ISSUE TITLE
failed writing

### ISSUE THREAD

**Issue by wjlei1990** [jas11/specfem3d_globe#5]
I have run a few jobs on titan but some of them failed.

I have attached log file here. Please have a look.
[job_sb.2568836.o.txt](https://github.com/jas11/specfem3d_globe/files/49277/job_sb.2568836.o.txt)

More details will be added later on.

**Comment by jas11** [comment]
________________________________________

**Comment by jas11** [comment]
Are you outputting SAC? 

"mv: cannot stat `OUTPUT_FILES/*.sac': No such file or directory"

Did you edit the Par_file to output SAC? Is this related to ASDF?



________________________________________

**Comment by wjlei1990** [comment]
No I only output asdf.

I am doing that cause I move both sac and asdf files to my data archive no matter what output format it is.

**Comment by wjlei1990** [comment]
Another thing, I am running the a bit old version(a few days ago)...I will test on the new one and see if it fix the problem.

I will let you know.

**Comment by jas11** [comment]
Can you post the CMTSOLUTION, Par_File, and STATIONS file and I will test it on Princeton's cluster
