### ISSUE TITLE
ASDF reader error

### ISSUE THREAD

**Issue by jas11** [jas11/specfem3d_globe#7]
Hi James,

After generate the adjoint source file, I can't get the adjoint solver running. The adjoint reader is giving me some error messeages. I have put my specfem and all related data at:
/lustre/atlas/proj-shared/geo111/Wenjie/James/specfem3d_globe

To get my stuff running, you do need to change one line in src/specfem3D/read_adjoint_sources_ASDF.f90.
  call ASDF_read_partial_waveform_f(current_asdf_handle, "AuxiliaryData/AdjointSources/"//&
        trim(adj_source_name) // C_NULL_CHAR, offset, nsamples, adj_source, ier)

I added an  s  in the path.

**Comment by jas11** [comment]
HI Wenjie,

The directories are empty and I get permission denied in any that aren't. Can you check that you copied them over using permissions I can access? Also it would speed things up if you can provide an adjoint source from pyadjoint that is read into specfem3d. That way I can focus on the problem of the reader in specfem3d_globe.

**Comment by wjlei1990** [comment]
Hi Could you check it again?

To reduce the waiting time, I reduce the resolution to 160. Please checkout my DATA/Par_file.

I put one adjoint source in SEM/synthetic.h5

It seems the path of adjoint sources are wrong.

**Comment by wjlei1990** [comment]
I changed the path back to "AuxilaryData/AdjointSource" because I found you encode the path also in the asdf-libary...

I update the `SEM/synthetic.h5`. Please have a look.

**Comment by jas11** [comment]
I can access the file. I was in the wrong directory.

**Comment by wjlei1990** [comment]
Great!

I couldn't locate the bug but obviously it is related to the path of adjoint source.

You can use either `h5dump -n synthetic.h5` or use ipython and pyasdf to read the files to check if the path is correct. You know how to do it...

Let me know if you need anything else.

**Comment by jas11** [comment]
I think I've fixed the problems with the reader. Can you provide a smaller adjoint source ASDF file so that I can test a full run on tiger first. Thanks!

**Comment by wjlei1990** [comment]
You mean smaller simulation time, right?

Cause the number of stations in adjoint asdf file doesn't matter, you can always change the STATIONS_ADJOINT file.

How long of the simulation do you want? I can't not make it too short otherwise it will be all zeros because of window time.

Or if you really want short ones(less than 10 mins seismograms), I can make up one for you. But it won't produce meaningfull kernels.

Best,
Wenjie
----------------------------------------------------
 Graduate student in Geophysics
 Princeton University | Guyot Hall 309
 Phone: 609-937-4659
________________________________

**Comment by jas11** [comment]
Yeah, ok. How about 10 minute seismograms?

**Comment by jas11** [comment]
I can actually do this myself also so if you're busy don't worry about it. I should have time tomorrow to test everything.

**Comment by wjlei1990** [comment]
I am going to make it 5 mins since if I guess for the seimogram with all zeros, 5mins and 10mins won't make a difference :)

**Comment by wjlei1990** [comment]
adjoint source and station file at: `/lustre/atlas/proj-shared/geo111/Wenjie/James/short_simulation`

**Comment by jas11** [comment]
Thanks, can you give me permission on the Par_file, STATIONS, and CMTSOLUTION ? The others are good

**Comment by wjlei1990** [comment]
Could you try now?

**Comment by jas11** [comment]
It works. Thanks!

________________________________

**Comment by jas11** [comment]
This is fixed now
