### ISSUE TITLE
make some files optional

### ISSUE THREAD

**Issue by wjlei1990** [jas11/specfem3d_globe#8]
Hi James,

Here:
https://github.com/jas11/specfem3d_globe/blob/devel/src/specfem3D/write_output_ASDF.f90#L401
I saw you add `constants.h` and `Par_file`. But could you make this two optional.

I mean, if the program can't find these two files, it can still run through without adding those two files. So you just need to check the existence of those two files and then add if there are.

Second, did you read those two files on all processors? I thing it is better to read in master node and then broadcast the file content.

**Comment by jas11** [comment]
Sounds good. I'll do this tonight.

**Comment by wjlei1990** [comment]
The way I want it to be modified is because of simultaneous run... The directory setup is a bit complicated. So it would be nice if adding those two files are optional.

**Comment by jas11** [comment]
I'm going to modify the library soon, but for now you can comment out if you don't wnat these files written (as you have already done)

**Comment by wjlei1990** [comment]
Do you need to modify the libaries? OK...Sounds complicated.

I thought you only need to modify the specfem?

If one file doesn't exist, just pull `null` string? >.<
